backend:
    name: github
    repo: ironnysh/11ty-test
    branch: master
    base_url: http://11ty-test.now.sh/
    auth_endpoint: api/begin
publish_mode: editorial_workflow
media_folder: "examples/common/images/uploads"
collections:
    - name: "pages"
      label: "Pages"
      folder: "examples/common/pages"
      create: true
      slug: "{{slug}}"
      fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}